name: DonatorExpress
main: net.targetcraft.donatorexpress.Main
version: 0.6.1
description: DonatorExpress
website: http://dev.bukkit.org/bukkit-plugins/donator-express/
author: aman207
authors: [AzroWear] 

commands:
    donate:
     description: General command for all of DonatorExpress's needs
     aliases: [donator, rank]
permissions:
    donexpress.*:
        description: Gives access to all commands
        children:
            donexpress.admin.*: true
            donexpress.user: true
            donexpress.user.upgrade: true
        default: op
    donexpress.admin.*:
        description: Access to all admin commands
        default: op
        children:
            donexpress.admin.edit: true
            donexpress.admin.checkvc: true
            donexpress.admin.add: true
            donexpress.admin.delete: true
            donexpress.admin.dbconnect: true
            donexpress.admin.addvc: true
            donexpress.admin.reload: true
            donexpress.admin.setvc: true
            donexpress.admin.recent: true
            donexpress.admin.update: true
            donexpress.user: true
            donexpress.user.upgrade: true
    donexpress.admin.basic:
        description: Basic access to admin commands
        default: op
        children:
            donexpress.admin.checkvc: true 
            donexpress.admin.ranklist: true
            donexpress.admin.dbconnect: true
    donexpress.admin.add:
        description: Adds a rank to the config
        default: op
    donexpress.admin.delete:
        description: Deletes a rank from the config
        default: op
    donexpress.admin.edit:
        description: Edits the amount of virtual currency for each rank
        default: op
    donexpress.admin.checkvc:
        description: Checks the amount of virtual currency that a player has
        default: op
    donexpress.admin.addvc:
        description: Adds virtual currency to a specified user
        default: op
    donexpress.admin.dbconnect:
        description: Manually connects to the database if its not working. 
        default: op
    donexpress.admin.reload:
        description: Reloads the config
        default: op
    donexpress.admin.setvc:
        description: Sets the amount of vc for a user. Not add
        default: op
    donexpress.admin.recent:
        description: Lets the player see the 5 most recent transactions
        default: op
    donexpress.admin.update:
        description: Notifies the user about an update
        default: op
    donexpress.user:
        description: Any commands that a user would use
        default: op
    donexpress.user.upgrade:
        description: Allows the user to upgrade their rank
        default: op